### ISSUE TITLE
BUFF dataset evaluation

### ISSUE THREAD

**Issue by MoyGcc** [CrisHY1995/StereoPIFu_Code#1]
Hi,

thanks for your amazing work. Could you please share the code snippet for the rendering and evaluation of the BUFF dataset? Many thanks in advance!

**Comment by CrisHY1995** [comment]
The rendering code of BUFF Dataset has been supplied in this Repository(https://github.com/CrisHY1995/StereoPIFu_Code/blob/main/GenEvalData.py#L105).

Please refer to the introduction of project page(https://github.com/CrisHY1995/StereoPIFu_Code) and run the command
```

python GenEvalData.py --color_mesh_path="TempData/SampleData/normalized_mesh_0089.off" --save_dir="./TempData/ColorMesh" --save_postfix="color"
```
Note: the mesh used for rendering needs to be scaled and let it located in a specific bounding box.

As to evaluation, because the related code is scattered, it might not be easy for you to use. Instead, we summarize  the main steps as follows:

1.     Register predicted mesh with GT mesh using this method (https://github.com/yaoyx689/Fast-Robust-ICP )

2.     Compute the Predict-to-GT/GT-to-Predict/Chamfer distance using pymesh library (https://pymesh.readthedocs.io/en/latest/api_geometry_processing.html),  the kernel function is “pymesh.distance_to_mesh(mesh, pts, engine='geogram')”

Best Wishes.
Yang.


title: [CrisHY1995/StereoPIFu_Code] BUFF dataset evaluation (#1)


Hi,

thanks for your amazing work. Could you please share the code snippet for the rendering and evaluation of the BUFF dataset? Many thanks in advance!

―

**Comment by CrisHY1995** [comment]
PS: 
1. Before registering, you need to delete free parts of the BUFF data except the main body.
2. Calculate the registration scale based on the y-axis range of the prediction result and the y-axis range of GT.

**Comment by MoyGcc** [comment]
> PS:
> 
> 1. Before registering, you need to delete free parts of the BUFF data except the main body.
> 2. Calculate the registration scale based on the y-axis range of the prediction result and the y-axis range of GT.

Many thanks!
