### ISSUE TITLE
Running eval.h with less than 10gb?

### ISSUE THREAD

**Issue by guayabas** [CrisHY1995/StereoPIFu_Code#5]
Is it possible to run the provided eval.sh sample with a single GPU that has less than 10gb? Changing some parameters in the code or using a different resolution for the images? or using a combo of 2 GPUs that equate to 10gb?

**Comment by CrisHY1995** [comment]
Because of 3D convolution, the calculation process does require a larger a larger graphic memory . In my impression, I seem to have tried some strategies, such as setting some parameter smaller,  to reduce the memory requirements of the eval process, but they did not effectively alleviate this problem well and the reduction is not obvious. 

Yang.

**Comment by guayabas** [comment]
sounds reasonable, thanks for the reply
